services:
  - type: web
    name: expense-tracker
    env: java
    region: frankfurt
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/ExpenseTracker-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: MAVEN_VERSION
        value: 3.9.0
      - fromGroup: expense-tracker-db
        key: DATABASE_URL
        sync: false
      - fromGroup: expense-tracker-db
        key: DATABASE_USER
        sync: false
      - fromGroup: expense-tracker-db
        key: DATABASE_PASSWORD
        sync: false

databases:
  - name: expense-tracker-db
    databaseName: expensetracker
    user: expenseuser
    plan: free
    ipAllowList: []