spring.datasource.url=jdbc:postgresql://localhost:5432/expenses_tracker?useUnicode=true&characterEncoding=UTF-8&currentSchema=expenses_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
