spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:expenses_tracker}?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never
spring.sql.init.encoding=UTF-8
server.port=${PORT:8080}